version: '3.7'
services:
  php:
    volumes:
    - './apps/back/:/usr/src/app'

  nginx:
    volumes:
    - './apps/back/public/:/usr/src/app'
    - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
    - '${NGINX_PORT}:80'

  adminer:
    ports:
    - '${ADMINER_PORT}:8080'