App\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            unique: true
            length: 100
        password:
            type: string
            nullable: false
            length: 255
        username:
            type: string
            unique: true
            nullable: false
            length: 30
        roles:
            type: json_array
            nullable: false
